audit_header: false
title: "Portland Metro & Southwest Washington's Best Real Estate Training - Nick Shivers"
description: Nick Shivers, a top Real Estate Agent in Portland Metro & Southwest Washington, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: Nick Shivers
  license_number:
  about_markdown: |
      As a principal broker in the top 1% of realtors nationwide, Nick Shivers leads the Nick Shivers Team at Keller Williams Realty Portland Central. His 18 years in the Portland Metro and Southwest Washington real estate markets has allowed him the privilege to serve thousands of clients. Our Mission is Serving People Saving Kids all by selling real estate. This mission has served us well by partnering with our clients through Sell a Home Save a child, something we co-founded. We have had the incredible opportunity to make a difference in the lives of hundreds of children. By donating a percentage of every closing, we are impacting the lives of children and building a brighter tomorrow.

  market: Portland Metro & Southwest Washington
  brand: The Nick Shivers Team
  brokerage: Keller Williams Realty Portland Central
  address: 6400 SE Lake Road, Suite 200 Portland, OR 97222
  address2: 5403 E Mill Plain Blvd. Vancouver, WA 98661
  phone: 866-596-NICK (6425)
  phone_type:
  phone2:
  phone2_type:
  email: sold@westonepros.com
  url: http://nickshivers.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how The Nick Shivers Team can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/nickshiversteam
  linkedin_url: https://www.linkedin.com/in/nickshivers/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCzKBdXDqBl5l47xRdvydgfQ?view_as=subscriber
  twitter_url: https://twitter.com/nickshivers
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Portland Metro & Southwest Washington Real Estate Podcast with Nick Shivers'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Portland Metro & Southwest Washington Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Nick Shivers Team - your professional Portland Metro & Southwest Washington Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Portland Metro & Southwest Washington, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Nick Shivers'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Portland Metro & Southwest Washington Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#000000'
  theme_color: '#E31D1A'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#E31D1A'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
